server:
  port: 8080

spring:
  application:
    name: orchestrator-service

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-service-group
      auto-offset-reset: latest